- README.md
- packages/protocols/src/rln.ts
- packages/protocols/tests/rln.test.ts
- README.md updates
- Inconsistencies between the Rln and NRln interfaces fixed
> README.md updates & inconsistencies fix

- packages/identity/src/identity.ts
- packages/protocols/tests/nrln.test.ts
> fix: identity multipart secret updates & nrln tests

- packages/protocols/README.md
- packages/protocols/src/utils.ts
- packages/protocols/tests/rln.test.ts
- packages/protocols/tests/semaphore.test.ts
> refactor: remove arity parameter from mt functions

- packages/protocols/src/index.ts
- packages/protocols/src/rln.ts
- packages/protocols/src/semaphore.ts
- packages/protocols/src/utils.ts
- packages/protocols/tests/rln.test.ts
> refactor: create signal hash fun for each protocol

- package.json
- packages/incremental-merkle-tree.sol/contracts/IncrementalBinaryTree.sol
- packages/incremental-merkle-tree.sol/contracts/IncrementalQuinTree.sol
- packages/incremental-merkle-tree.sol/contracts/README.md
- packages/incremental-merkle-tree.sol/contracts/test/IncrementalBinaryTreeTest.sol
- packages/incremental-merkle-tree.sol/contracts/test/IncrementalQuinTreeTest.sol
- packages/incremental-merkle-tree.sol/test/IncrementalBinaryTreeTest.ts
- packages/incremental-merkle-tree.sol/test/IncrementalQuinTreeTest.ts
- yarn.lock
`@zk-kit/incremental-merkle-tree` has an update method, but `@zk-kit/incremental-merkle-tree.sol` does not. this pr adds the functionality to the solidity contract.
-   [ ] Yes
-   [X] No
Basic unit tests included!
> feat: add update function to @zk-kit/incremental-merkle-tree.sol

- packages/incremental-merkle-tree.sol/contracts/IncrementalBinaryTree.sol
- packages/incremental-merkle-tree.sol/contracts/IncrementalQuinTree.sol
- yarn.lock
This PR replace the `remove` function body with a single line of code, in which the `update` function is called to update the leaf with a zero value.
Closes #30 
-   [ ] Yes
-   [x] No
> New remove function

- packages/incremental-merkle-tree.sol/contracts/README.md
update readme file
-   [ ] Yes
-   [x] No
> docs: update readme

- packages/incremental-merkle-tree.sol/contracts/IncrementalBinaryTree.sol
- packages/incremental-merkle-tree.sol/scripts/defaultZeroes.mjs
- packages/incremental-merkle-tree.sol/test/IncrementalBinaryTreeTest.ts
Fix a typo in the incremental merkle tree tests. Change how default zero values are access (if statements instead of in memory).
Also removes a storage access from the inside of a loop in the insert function.
-   [ ] Yes
-   [x] No
> Tree fixes

- packages/incremental-merkle-tree.sol/contracts/IncrementalBinaryTree.sol
- packages/incremental-merkle-tree.sol/contracts/test/IncrementalBinaryTreeTest.sol
Return the new root of the tree during insert.
Closes #45 
-   [x] Yes
-   [ ] No
> feat(incremental-merkle-tree.sol): return root on insert

- packages/incremental-merkle-tree.sol/contracts/package.json
- packages/incremental-merkle-tree.sol/package.json
- yarn.lock
> Bump Poseidon Solidity dependency

- packages/incremental-merkle-tree/src/createProof.ts
- packages/incremental-merkle-tree/src/types/index.ts
- packages/incremental-merkle-tree/tests/index.test.ts
Closes #62 
-   [ ] Yes
-   [x] No
> feat(incremental-merkle-tree): add leafIndex to merkle proof

- packages/rollup-plugin-rust/package.json
- yarn.lock
fix #79
-   [ ] Yes
-   [x] No
> Add missing `toml` npm package in `rollup-plugin-rust` package

- .github/workflows/production.yml
- .github/workflows/pull-requests.yml
- README.md
- package.json
- packages/eddsa-poseidon/LICENSE
- packages/eddsa-poseidon/README.md
- packages/eddsa-poseidon/build.tsconfig.json
- packages/eddsa-poseidon/package.json
- packages/eddsa-poseidon/rollup.config.ts
- packages/eddsa-poseidon/rollup.iife.config.ts
- packages/eddsa-poseidon/src/babyjub.ts
- packages/eddsa-poseidon/src/blake.ts
- packages/eddsa-poseidon/src/eddsa-poseidon.ts
- packages/eddsa-poseidon/src/field.ts
- packages/eddsa-poseidon/src/field1.ts
- packages/eddsa-poseidon/src/index.ts
- packages/eddsa-poseidon/src/scalar.ts
- packages/eddsa-poseidon/src/types/index.ts
- packages/eddsa-poseidon/src/utils.ts
- packages/eddsa-poseidon/tests/index.test.ts
- packages/eddsa-poseidon/tsconfig.json
- packages/eddsa-poseidon/typedoc.json
- yarn.lock
[README.md](https://github.com/privacy-scaling-explorations/zk-kit/blob/main/packages/eddsa-poseidon/README.md
)
Closes #87
-   [ ] Yes
-   [x] No
> JS EdDSA Poseidon implementation

- packages/circuits/.gitattributes
Create .gitattributes for Noir syntax highlighting on Github
-   [ ] Yes
-   [x] No
> Create .gitattributes for Noir syntax highlighting

- package.json
- packages/imt.sol/LICENSE
- packages/imt.sol/contracts/LICENSE
- packages/imt.sol/contracts/README.md
- packages/imt.sol/contracts/package.json
- packages/imt/LICENSE
- packages/imt/README.md
- packages/imt/package.json
- packages/lazytower.circom/LICENSE
- packages/lazytower.circom/README.md
- packages/lazytower.circom/package.json
- packages/lazytower.sol/LICENSE
- packages/lazytower.sol/contracts/LICENSE
- packages/lazytower.sol/contracts/README.md
- packages/lazytower/LICENSE
- packages/lazytower/README.md
- packages/lazytower/package.json
- packages/rollup-plugin-rust/LICENSE
- packages/rollup-plugin-rust/README.md
- packages/rollup-plugin-rust/package.json
- packages/smt/LICENSE
- packages/smt/README.md
- packages/smt/package.json
Closes #82 
-   [ ] Yes
-   [x] No
> Specific licence for each zk-kit package

- packages/eddsa-poseidon/README.md
- packages/eddsa-poseidon/src/eddsa-poseidon.ts
> New function to calculate the secret scalar S

- packages/eddsa-poseidon/README.md
- packages/eddsa-poseidon/src/babyjub.ts
- packages/eddsa-poseidon/src/eddsa-poseidon.ts
- packages/eddsa-poseidon/src/field.ts
- packages/eddsa-poseidon/src/scalar.ts
- packages/eddsa-poseidon/src/sqrt.ts
- packages/eddsa-poseidon/tests/index.test.ts
> New EdDSAPoseidon functions to pack/unpack pub keys

- .github/workflows/production.yml
- .github/workflows/pull-requests.yml
This PR updates CI environment to use current LTS of Node.js
-   [ ] Yes
-   [x] No
> ci: use LTS of node.js

- packages/circuits/circom/binary-merkle-root.circom
- packages/circuits/tests/binary-merkle-root.test.ts
Closes #113 
-   [ ] Yes
-   [x] No
> Additional check for when depth equals MAX_DEPTH

- .github/workflows/docs.yml
- .github/workflows/production.yml
- .github/workflows/pull-requests.yml
Closes #118 
-   [ ] Yes
-   [x] No
> Remove unnecessary cache action from workflows

- README.md
- packages/groth16/README.md
This PR removes `@zk-kit/groth16` from the list of packages in the main README file, and adds a warning to the package's README file.
Closes #145
> Deprecate `@zk-kit/groth16` package

- packages/baby-jubjub/README.md
- packages/circuits/README.md
- packages/eddsa-poseidon/README.md
- packages/eddsa-proof/README.md
- packages/groth16/README.md
- packages/imt/README.md
- packages/imt/package.json
- packages/poseidon-cipher/README.md
- packages/poseidon-proof/README.md
- packages/smt/README.md
This PR aims to provide:
- An explanation of different Merkle trees implementations + an update for the usage section of the `imt` package.
- Add missing circuits to the `circuits` package README file list.
- Add `usage` section to the `poseidon-cipher` package.
closes #83 
> Check and improve READMEs

- packages/baby-jubjub/package.json
- packages/baby-jubjub/src/baby-jubjub.ts
- packages/baby-jubjub/tests/index.test.ts
- packages/eddsa-poseidon/package.json
- packages/eddsa-poseidon/tests/index.test.ts
- yarn.lock
This PR replaces the implicit conversions from LE to BE in the `packPoint`/`unpackPoint` functions with the utility function to convert in LE. More info and context in #154.
Fixes #154
> No implicit conversions in `packPoint`/`unpackPoint` functions

- packages/baby-jubjub/src/baby-jubjub.ts
- packages/baby-jubjub/src/sqrt.ts
- packages/baby-jubjub/tests/index.test.ts
This PR adds more documentation to the `baby-jubjub` package, with the aim of enhancing the code readability with meaningful information.
closes #142 
This PR adds the missing tests to reach the 98.88% code coverage.
-   [x] Any dependent changes have been merged and published in …
> More documentation and tests on `@zk-kit/baby-jubjub` package

- packages/eddsa-poseidon/src/blake.ts
- packages/eddsa-poseidon/src/eddsa-poseidon.ts
- packages/eddsa-poseidon/src/utils.ts
- packages/eddsa-poseidon/tests/index.test.ts
This PR adds more documentation to the `eddsa-poseidon` package, with the aim of enhancing the code readability with meaningful information.
closes #140 
This PR adds the missing tests to reach the 100% code coverage.
-   [x] Any dependent changes have been merged and published …
> More documentation and tests on `@zk-kit/eddsa-poseidon` package

- .commitlintrc.js
- .commitlintrc.json
- .husky/prepare-commit-msg
- CONTRIBUTING.md
- README.md
- package.json
- yarn.lock
This PR replaces the old cz plugin with [`cz-git`](https://github.com/Zhengqbbb/cz-git), and makes the `git commit` command interactive by default so that devs will be forced to write standard conventional commits. 
Closes #191 
-   [ ] Any dependent changes have been merged and …
> Improve interactive conventional commits

- packages/circuits/circom/circuits.json
- packages/circuits/circom/float.circom
- packages/circuits/tests/float.test.ts
This PR adds the float math library (`MSB`, `Shift`, `IntegerDivision`, `ToFloat`, `DivisionFromFloat`, `DivisionFromNormal`, `MultiplicationFromFloat`, `MultiplicationFromNormal`) circom templates.
Compared to the original version of MACI, Anonymous Components were used, resulting in DX improvement and small optimisation (labels).
see #131 
- …
> Add float math circuits

- packages/eddsa-poseidon/src/utils.ts
- packages/utils/src/conversions.ts
- packages/utils/src/type-checks.ts
- packages/utils/src/types/index.ts
- packages/utils/tests/conversions.test.ts
The utility functions in the conversions module now check their parameter types before converting any value.
Parameters have also been renamed to 'value', to make them more consistent with the other modules.
Additionally, support for Uint8Array buffers has been added, when the input is a buffer.
Closes #187
-   [x] New and existing unit tests …
> Require right types in `conversions` module

- packages/utils/src/conversions.ts
- packages/utils/tests/conversions.test.ts
`Buffer.from` needs a hexadecimal string with an even length. If the length is odd it does not consider the first byte. This PR ensures the length is always even.
Additionally, it removes "be" occurrences from functions without "le"/"be" alternatives.
Fixes #204
-   [x] Any …
> Ensure even length before converting hexadecimal strings to buffer

- packages/circuits/circom/binary-merkle-root.circom
Closes https://github.com/privacy-scaling-explorations/zk-kit/issues/211
> add a warning for `depth > MAX_DEPTH`

- packages/imt.sol/contracts/README.md
- packages/imt/README.md
Now it's easier to find the visual explanation of the LeanIMT data structure.
Closes #216
> Docs: Add the leanimt hackmd file to imt and imt.sol readme files

- tsconfig.json
> Update TypeScript target to `es2020`

- packages/circuits/tests/common.ts
Fix imt test to use the correct depth and the correct leaf.
> test(circuits): fix imt circuit tests to use variable depth and correct leaf

- .github/workflows/docs.yml
- .github/workflows/production.yml
- .github/workflows/pull-requests.yml
This PR introduces several optimizations to our CI pipeline.
- remove redundant dependencies
- skip unnecessary dependency installations
- disable fail-fast to continue tests after a failure; even if one fails, ensuring comprehensive test results
- cancel obsolete CI runs when a new commit is pushed to a PR
Closes #266
> ci: optimize CI behavior

- .husky/pre-commit
- .husky/prepare-commit-msg
- .lintstagedrc.json
- package.json
- yarn.lock
This PR updates the repo config.
Closes #278 
-   [ ] My code follows the style guidelines of this project
-   [ ] I have performed a self-review of my code
-   [ ] My changes generate no new warnings
-   [ ] I have run `yarn style` without getting any errors
> chore: update config

- packages/eddsa-poseidon/src/eddsa-poseidon.ts
Some comments related to old code have been removed.
> refactor(eddsa-poseidon): remove old comments

- packages/circuits/circom/ecdh.circom
- packages/circuits/noir/merkle_trees/src/merkle/tree.nr
- packages/imt.sol/test/LazyIMT.ts
fix some duplicate words in comment.
> chore: remove duplicate words

- packages/poseidon-proof/package.json
- yarn.lock
see https://github.com/privacy-scaling-explorations/snark-artifacts/pull/57
> chore: bump `@zk-kit/artifacts`

- packages/utils/src/conversions.ts
- packages/utils/tests/conversions.test.ts
This PR adds 4 functions to convert base64 strings from buffers and text.
Closes #299
> feat(utils): add new functions to convert base64 strings

- packages/lean-imt/README.md
- packages/lean-imt/src/lean-imt.ts
- packages/lean-imt/tests/lean-imt.test.ts
The `import` function was made static and a parameter was added to convert node types.
Closes #312
Please notice that this PR introduces a breaking change.
> refactor(lean-imt)!: update function to import exported trees

- README.md
> docs: update merkle trees section

- benchmarks/benchmark-merkle-trees.ts
fix some typos in comment
-   [ ] My changes generate no new warnings
-   [ ] I have run `yarn style` without getting any errors
> chore(benchmarks): fix some typos in comment

- .husky/commit-msg
- .husky/pre-commit
- .husky/prepare-commit-msg
The following lines in the husky scripts have been removed as they are not necessary anymore and will make husky fail in v10.0.0.
```bash
#!/usr/bin/env sh
. "$(dirname -- "$0")/_/husky.sh"
```
> chore: remove unnecessary husky code

- packages/imt/src/imt.ts
> docs(imt): add docs to indexOf function

- benchmarks/benchmark-merkle-trees.ts
I've refactored the benchmarking code to enhance maintainability and readability. The key changes include:
- **Eliminated Code Duplication:** ntroduced a new function, `benchmarkSuite`, to encapsulate the common logic for creating and running benchmarks. This reduces repetitive code and simplifies future maintenance.
- **Improved Readability:** treamlined and shortened certain code blocks, making them more concise and easier to understand.
- **Optimized Performance:** educed the number of `logger.error` calls by passing the benchmark name directly to the `benchmarkSuite` function.
hese updates retain all original functionalities while making the script more compact and maintainable.
-   [x] I have read and understand the [contributor …
> refactor: consolidated benchmark logic into benchmarkSuite function

- .github/pull_request_template.md
- CONTRIBUTING.md
- LICENSE
This PR updates the contributing file and license year.
Re #396
-   [x] I have read and understand the [contributor guidelines](https://github.com/privacy-scaling-explorations/zk-kit/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/privacy-scaling-explorations/zk-kit/blob/main/CODE_OF_CONDUCT.md).
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., correcting typos, rewording sentences) …
> docs: update contributing
