- packages/protocols/src/rln.ts
- packages/protocols/src/semaphore.ts
- packages/protocols/src/types/index.ts
- packages/protocols/src/zk-protocol.ts
- packages/protocols/tests/rln.test.ts
- packages/protocols/tests/semaphore.test.ts
The generated proof using snarkjs will return an object of type PublicSignals for the public signals
instead of the array
BREAKING CHANGE: The generated proof using snarkjs will return an object of type PublicSignals for
the public signals instead of the array
The generated proof using snarkjs returns an array of the public signals, the same array returned by snarkjs.
Issue Number: N/A
The generated proof using snarkjs will return an object of type PublicSignals for the public signals
instead of the array
-
-
-
Existing applications should update the way they access the public signals.
> feat(zk-protocol): structure the public signals array obtained while generating a proof from snarkjs

- packages/incremental-merkle-tree/package.json
- packages/incremental-merkle-tree/src/insert.ts
- packages/incremental-merkle-tree/tests/index.test.ts
- packages/protocols/package.json
- packages/protocols/src/utils.ts
- packages/protocols/tests/rln.test.ts
The incremental-merkle-tree can be constructed with any value, including zeros. The generation of
merkle proof will fail for zero value.
Current behavior doesn't allow the creation of a merkle tree with a zero leaf.
Issue Number: N/A
The new behavior allows the creation of a merkle tree with a zero leaf, while the generation of a merkle proof for a zero commitment will fail.
> fix(incremental-merkle-tree): merkle tree supports zero leaves. Merkle proof fails for zero value

- packages/identity/package.json
- packages/identity/src/utils.ts
- packages/identity/yarn.lock
- packages/sparse-merkle-tree/README.md
- packages/sparse-merkle-tree/package.json
- packages/sparse-merkle-tree/tests/index.test.ts
- packages/sparse-merkle-tree/yarn.lock
`js-sha256` hasn't been updated for a long time. It causes frontend `referenceError` in some config.
Issue Number: N/A
- Use `crypto-js/sha256` instead of `js-sha256`
- hash element with `sha256(message)`
- stringify sha256 hash with `.toString()`
> chore: use `crypto-js/sha256` instead of `js-sha256`

- packages/incremental-merkle-tree.sol/contracts/IncrementalBinaryTree.sol
- packages/incremental-merkle-tree.sol/contracts/IncrementalQuinTree.sol
A few gas optimizations
- Caching storage variable in memory to avoid multiple `SLOAD`s
- Converting `depth` from `uint8` to `uint256` to avoid extra unpacking.
- Use `unchecked` for loop counter.
https://github.com/privacy-scaling-explorations/zk-kit/issues/27
-   [ ] Yes
-   [x] No
> refactor(incremental-merkle-tree.sol): gas optimizations

- packages/incremental-merkle-tree.sol/contracts/IncrementalBinaryTree.sol
- packages/incremental-merkle-tree.sol/contracts/IncrementalQuinTree.sol
- packages/incremental-merkle-tree.sol/test/IncrementalBinaryTreeTest.ts
- packages/incremental-merkle-tree.sol/test/IncrementalQuinTreeTest.ts
This PR fixes a bug in the `@zk-kit/incremental-merkle-tree.sol` package. You can find more info in the related issue. 
Closes #35
-   [ ] Yes
-   [x] No
This bug was found by Veridise during their audit of Semaphore.
> Additional checks for new leaves in the update function

- packages/incremental-merkle-tree.sol/contracts/IncrementalBinaryTree.sol
- packages/incremental-merkle-tree.sol/contracts/IncrementalQuinTree.sol
- packages/incremental-merkle-tree.sol/test/IncrementalBinaryTreeTest.ts
- packages/incremental-merkle-tree.sol/test/IncrementalQuinTreeTest.ts
This PR adds a `require` to check if the path indices of a proof of membership are the right numbers.
Closes #37 
-   [ ] Yes
-   [x] No
This bug was found by [Veridise](https://veridise.com/) during their audit of Semaphore.
> New checks for path indices

- packages/hashtower.sol/contracts/package.json
- packages/hashtower.sol/package.json
- packages/incremental-merkle-tree.sol/contracts/package.json
- packages/incremental-merkle-tree.sol/package.json
- yarn.lock
The new poseidon-solidity is ~9% cheaper for `PoseidonT2`/`PoseidonT3`
-   [ ] Yes
-   [x] No
> chore: bump poseidon-solidity

- packages/incremental-merkle-tree/README.md
- packages/incremental-merkle-tree/src/incremental-merkle-tree.ts
- packages/incremental-merkle-tree/tests/index.test.ts
This PR adds a new parameter to the `IncrementalMerkleTree` JS class to allow devs to efficiently add a list of leaves without the need to add them manually with the `insert` function and then avoiding calculating the same hashes/non-leaf nodes a number of times equal to the tree arity.
-   [ ] Yes
-   [x] No
> New parameter to init tree with a list of leaves

- packages/incremental-merkle-tree.sol/contracts/LazyMerkleTree.sol
- packages/incremental-merkle-tree.sol/contracts/test/LazyMerkleTreeTest.sol
- packages/incremental-merkle-tree.sol/hardhat.config.ts
- packages/incremental-merkle-tree.sol/tasks/deploy-lmt-test.ts
- packages/incremental-merkle-tree.sol/test/LazyMerkleTree.ts
Adds a `LazyMerkleTree` contract that builds a variable depth merkle tree. The depth increases as the tree becomes more full. The tree can have a max capacity set during initialization. The tree can also be reset and re-used in constant time.
-   [ ] Yes
-   [x] No
> feat(incremental-merkle-tree.sol): lazy merkle tree implementation

- packages/incremental-merkle-tree.sol/contracts/LazyMerkleTree.sol
- packages/incremental-merkle-tree.sol/contracts/test/LazyMerkleTreeTest.sol
- packages/incremental-merkle-tree.sol/test/LazyMerkleTree.ts
Overloads the `root` function in `LazyMerkleTree` to accept an optional depth.
-   [ ] Yes
-   [x] No
> Calculate root for variable heights

- .github/workflows/pull-requests.yml
- packages/circuits/README.md
- packages/circuits/noir/Nargo.toml
- packages/circuits/noir/crates/smt_bn254/Nargo.toml
- packages/circuits/noir/crates/smt_bn254/src/lib.nr
- packages/circuits/noir/crates/smt_bn254/src/utils.nr
- packages/circuits/package.json
Includes a Noir circuit library based on the BigNumber smt JS implementation in `packages/smt`. The library includes functions for:
- verifying (non-)membership proofs
- adding a new entry
- deleting an existing entry
- updating an existing entry
Since it's written as a library and intended to be used in other circuits, I haven't added compilation scripts. More info about Noir libraries [here (had to use the webarchive because noir docs are down atm^^) ](https://web.archive.org/web/20231021012840/https://noir-lang.org/modules_packages_crates/crates_and_packages#libraries).
#89 
-   [ ] Yes
-   [x] No
> Adds Noir library for BN SMT `verify`, `add`, `update`, `delete`

- packages/groth16/package.json
- packages/imt/package.json
- packages/lazytower/package.json
- packages/poseidon-proof/package.json
- packages/smt/package.json
Closes #84 
-   [ ] Yes
-   [x] No
> New NPM `types` field inside `exports`

- packages/imt.sol/contracts/internal/InternalLeanIMT.sol
Change `rightmostNodes ` -> `sideNodes` variable name and description.
#102 
-   [ ] Yes
-   [x] No
> Change variable name and description

- packages/eddsa-poseidon/src/babyjub.ts
Using `F.e` inside `mulPointEscalar` generates different outputs than `circomlibjs`. It will eventually be removed after a security review.
-   [x] Yes
-   [ ] No
> Remove `F.e` method inside `mulPointEscalar` 

- README.md
- packages/poseidon-cipher/package.json
- yarn.lock
Fix workspace imports which cause the package to not be installed and add the package to the main README
-   [ ] Yes
-   [x] No
> fix(poseidon-cipher): fix depedency imports and add package to root README

- packages/imt.sol/contracts/LazyIMT.sol
- packages/imt.sol/contracts/LeanIMT.sol
- packages/imt.sol/contracts/QuinaryIMT.sol
- packages/imt.sol/contracts/internal/InternalLeanIMT.sol
- packages/imt.sol/contracts/test/LeanIMTTest.sol
- packages/imt.sol/test/LeanIMT.ts
Closes #81 
-   [ ] Yes
-   [x] No
> Add `insertMany` function in LeanIMT

- packages/baby-jubjub/src/baby-jubjub.ts
- packages/baby-jubjub/tests/index.test.ts
When converting a packed point with less than 32 bytes from bigint to hex or buffer it is necessary to pad it so that the number of bytes is always 32. 
-   [ ] Yes
-   [x] No
> Packed points with less than 32 bytes are now padded

- packages/circuits/circom/circuits.json
- packages/circuits/circom/ecdh.circom
- packages/circuits/tests/ecdh.test.ts
Implement a circom circuit that allows to generate a shared secret from a private key and a public key.
-   [ ] Yes
-   [x] No
> feat(ecdh): implement ECDH circom circuit

- packages/poseidon-cipher/package.json
- packages/poseidon-cipher/src/poseidonCipher.ts
- packages/poseidon-cipher/tests/index.test.ts
- yarn.lock
Implement copy of circuit.decryptWithoutCheck to replicate circuit logic in TS.
-   [ ] Yes
-   [x] No
> feat(poseidon-cipher): add decrypt without checks to not throw on failure

- packages/utils/package.json
- packages/utils/src/number-conversions.ts
- packages/utils/tests/number-conversions.test.ts
- yarn.lock
4 changes here, in order of importance:
1) While testing compatibility of zk-kit with circomlibjs, I discovered that `leBufferToBigint` has a side-effect of reversing its input.  This was surprising when I was trying to use the same input multiple times and compare results.  Fixing this introduces an extra copy of 32 bytes, but I think that's worthwhile to avoid the risk of bugs.  There are larger costs for the use of hex coversion via strings.
2) While testing this, I also noticed that `bigintToBuffer` doesn't always pad its results to 32 bytes, resulting in incorrect conversions.  I fixed this as well using an offset to the copy command.  These conversion functions seem to be intended for fixed-size numbers of 32 byes.  I'd recommend adding some more checks that input bigints aren't too …
> fix(utils): input mutations and small-number padding in BigInt <-> Buffer conversions

- packages/imt.sol/contracts/internal/InternalLazyIMT.sol
- packages/imt.sol/test/LazyIMT.ts
Fixes an overflow when checking number of leaves for a depth.
Related #135 
-   [ ] Yes
-   [x] No
> fix: lazy imt depth overflow

- packages/imt/src/lean-imt/lean-imt.ts
- packages/imt/src/lean-imt/utils.ts
- packages/imt/tests/lean-imt.test.ts
This PR implements two new methods in the LeanIMT class: `import` and `export`. You can find more information in the related issue.
Closes #155 
> New LeanIMT `import`/`export` methods

- packages/eddsa-proof/package.json
- packages/eddsa-proof/src/generate.ts
- packages/eddsa-proof/src/hash.ts
- packages/eddsa-proof/src/types/index.ts
- packages/eddsa-proof/src/unpack-proof.ts
- packages/eddsa-proof/src/verify.ts
- packages/poseidon-proof/package.json
- packages/poseidon-proof/src/generate.ts
- packages/poseidon-proof/src/hash.ts
- packages/poseidon-proof/src/pack-proof.ts
- packages/poseidon-proof/src/types/index.ts
- packages/poseidon-proof/src/unpack-proof.ts
- packages/poseidon-proof/src/verify.ts
- yarn.lock
> Replace `groth16` dependency with `snarkjs` in `eddsa-proof` and `poseidon-proof`

- packages/circuits/circom/circuits.json
- packages/circuits/circom/safe-comparators.circom
- packages/circuits/tests/safe-comparators.test.ts
This PR adds the safe comparators (`SafeLessThan`, `SafeLessEqThan`, `SafeGreaterThan`, `SafeGreaterEqThan`) circom templates. These circuits are pretty much similar to the [circomlib](https://github.com/iden3/circomlib/blob/cff5ab6288b55ef23602221694a6a38a0239dcc0/circuits/comparators.circom) ones but they add a conversion of the inputs to compare to their bit representations to ensure they fit within 'n' bits (implicit range check).
Compared to the original version of MACI, Anonymous Components were used, resulting in DX improvement and small optimisation.
see #131 
-   [x] I have made corresponding …
> feat: add safe comparators templates

- packages/circuits/circom/circuits.json
- packages/circuits/circom/unpack-element.circom
- packages/circuits/tests/unpack-element.test.ts
This PR adds the `UnpackElement` circom template. This circuit allows a single field element to be converted into multiple 50-bit elements. 
Compared to the original version of MACI, Anonymous Components were used, resulting in DX improvement and small optimisation.
see #131 
- …
> Add `UnpackElement` circuit

- packages/utils/src/conversions.ts
- packages/utils/src/error-handlers.ts
- packages/utils/src/type-checks.ts
- packages/utils/tests/conversions.test.ts
- packages/utils/tests/error-handlers.test.ts
- packages/utils/tests/type-checks.test.ts
This PR adds 4 functions to the `conversions` module to convert hexadecimal strings to buffers and vice versa, both using little-endian and big-endian byte orders.
It also adds `isBuffer` to the `type-checks` module, and a `requireBuffer` to the `error-handlers` module.
Finally, it adds a new `prefix` parameter to the `isHexadecimal` and `requireHexadecimal` functions. It is an optional boolean (set to `true` by default) to consider or not the `0x` or `0X` prefix in a hexadecimal string.
Closes #189
- …
> Add new utility functions to convert hex and buffers

- packages/eddsa-poseidon/src/eddsa-poseidon.ts
- packages/eddsa-poseidon/tests/index.test.ts
If no private key is passed to the constructor, a 32-byte random buffer will be generated for it.
Closes #183
> Generate a random EdDSA private key if it is not provided by devs

- packages/eddsa-poseidon/src/utils.ts
- packages/eddsa-poseidon/tests/index.test.ts
- packages/utils/src/error-handlers.ts
- packages/utils/src/type-checks.ts
- packages/utils/tests/error-handlers.test.ts
- packages/utils/tests/type-checks.test.ts
Added `isBigNumber` and `requireBigNumber` in zk-kit/utils
Used `isBigNumber` in `isPoint` and `isSignature` in zk-kit/eddsa-poseidon to make them more accepting
Fixes #198
> fix(eddsa-poseidon): eddsa-poseidon should accept Points and Signatures in numeric form

- packages/eddsa-poseidon/src/eddsa-poseidon.ts
- packages/eddsa-poseidon/tests/index.test.ts
Signatures are packed into 64 bytes using the same format as circomlibjs.  Unit tests confirm the compatibility of output.
There's a TODO in place for one more unit test I'd like to add after #200 lands and fixes the ability to accept signatures in numeric form.
The unpackSignature function returns a `Signature<string>`.  If #199 gets accepted and implemented, it should change to return `Signature<bigint>`.
> feat(eddsa-poseidon): add packSignature and unpackSignature to eddsa-poseidon

- packages/circuits/tests/float.test.ts
This PR optimizes the tests for the `float.circom` templates working on a <= 32 bits math instead of 252 bits.
> test(circuits): optimize `float.circom` tests

- packages/circuits/tests/common.ts
- packages/circuits/tests/ecdh.test.ts
- packages/circuits/tests/eddsa-proof.test.ts
- packages/circuits/tests/poseidon-cipher.test.ts
- packages/eddsa-poseidon/src/eddsa-poseidon.ts
- packages/eddsa-poseidon/src/utils.ts
- packages/eddsa-poseidon/tests/index.test.ts
- packages/eddsa-proof/src/generate.ts
- packages/eddsa-proof/tests/index.test.ts
- packages/poseidon-cipher/tests/index.test.ts
- packages/poseidon-cipher/tests/utils.ts
Breaking change ⚠️ 
Types supported for the EdDSA private key have been reduced to 3: Buffer, Uint8Array, and string, i.e. buffers or text.
Closes #188
> Restrict EdDSA private-key supported types

- packages/imt.sol/contracts/internal/InternalLeanIMT.sol
A new insertion can increase a tree's depth by at most 1. We can be sure that the while loop isn't executed twice.
Closes #213
> Use `if` instead of `while` to increment depth in the `LeanIMT.insert` function

- packages/imt.sol/contracts/internal/InternalLeanIMT.sol
- packages/imt.sol/test/LeanIMT.ts
Updating LeanIMT of size 1 (tree with 1 leaf inserted), the update function should not revert. This PR removes that check.
Fixes #210
> Remove merkle proof length check in the `update` function

- packages/imt/src/imt/imt.ts
- packages/imt/src/lean-imt/lean-imt.ts
- packages/imt/tests/imt.test.ts
- packages/imt/tests/lean-imt.test.ts
re #218
Adds static versions of `verifyProof` on `IMT` and `LeanIMT` so that it's not necessary to create an IMT object just to verify an existing proof.  Existing instance method still exists (to avoid breaking change) and calls the static one.  Also clarified in docs that the instance method doesn't check that the proof comes from this specific tree (i.e. no checking of root).
Closes #218
-   [x] I have added tests that …
> feat(imt): add static version of IMT verifyProof

- packages/imt.sol/contracts/README.md
- packages/imt.sol/contracts/internal/InternalLeanIMT.sol
- packages/imt.sol/test/LeanIMT.ts
The `indexOf` function throws a custom error when a leaf does not exist now. It was throwing an unspecified error previously.
Closes #206
> Handle `LeanIMT.indexOf` exception when a leaf does not exist

- packages/imt.sol/contracts/internal/InternalLeanIMT.sol
- packages/imt.sol/test/LeanIMT.ts
This PR:
- Adds a check to the `_update` function in the `InternalLeanIMT.sol` file to update the `newLeaf` index only if `newLeaf` is different from 0. Now when trying to update a removed leaf the transaction will revert with the custom error `LeafDoesNotExist`. 
- Removes unnecessary `newLeaf != 0` check. Since the _has function will no longer return true for the leaf 0, this check is no longer
necessary.
- Adds new tests to cover 100% of the lines of `InternalLeanIMT.sol`,
Closes #228
-   [x] I …
> Update removed nodes

- packages/imt.sol/contracts/LazyIMT.sol
- packages/imt.sol/contracts/internal/InternalLazyIMT.sol
- packages/imt.sol/contracts/test/LazyIMTTest.sol
- packages/imt.sol/test/LazyIMT.ts
This PR adds a function to the `LazyIMT` contract, `_merkleProofElements`, which returns the Merkle proof of any leaf `index` in the tree. The `depth` is configurable, which allows to get the proofs of any subtree.
Closes https://github.com/privacy-scaling-explorations/zk-kit/issues/123
> feat: add get merkle proof to lazy imt tree

- packages/utils/src/f1-field.ts
F1Field.e(res) checks if it is >= this._order to determine if it needs to take a modulus with this._order. However, in v8 bigint implementation, this check is already present. So this check is not necessary as bigint implementation already does that. This commit removes these checks.
https://github.com/v8/v8/blob/497d8573dc80b1b69052a834bec894cf5d4238e7/src/builtins/builtins-bigint.tq#L380-L383
I was just reading zk-kit's F1Field code after studying modular arithmetic. Please let me know if this is useful!
-   [x] My changes generate no new …
> refactor(utils): update F1Field.e(res) function to remove the comparison checks with this._order

- packages/utils/src/f1-field.ts
- packages/utils/tests/f1-field.test.ts
This PR doesn't fix #241. In order to keep the F1Field functions light and more efficient devs should check themselves if the input values are within the field. A comment has been added to the module to be more explicit.
This PR also updates tests by removing unnecessary `BigInt` conversions.
Closes #241
-   [ ] New and existing unit tests pass locally with my …
> More comments for explicit mod reduction on inputs

- .github/workflows/production.yml
- .github/workflows/pull-requests.yml
Pins Noir version in github actions to 0.26.0, this ensures Noir tests won't fail randomly (famous last words...)
> fix(github actions): pin noir version to 0.26.0

- packages/eddsa-poseidon/src/eddsa-poseidon.ts
The secret scalar is used to derive the public key and it must be > l, where l is the sub-order used in Baby Jubjub. Adding a mod reduction ensures it always stays in the right range by keeping it compatible with the existing public keys.
Fixes #239
-   [ ] Any dependent changes have been merged …
> Add mod reduction in secret scalar generation

- packages/eddsa-poseidon/src/eddsa-poseidon.ts
- packages/lazytower/src/lazytower-hash-chain-proof-builder.ts
- packages/poseidon-proof/src/verify.ts
- packages/smt/src/smt.ts
- packages/utils/src/type-checks.ts
- typedoc.js
- typedoc.json
Fix different warnings shown when building the docs.
Fixes #258
|Before|After|
|--|--|
|`yarn docs`: builds successfully but generates a bunch of warnings|`yarn docs`: builds successfully without warnings|
> docs: fix `typedoc` compilation warnings

- packages/imt.sol/test/LazyIMT.ts
* Increases timeout of `Should produce valid Merke proofs for different trees` test from `5minutes` to `6minutes` to fix [intermittent timeouts](https://github.com/privacy-scaling-explorations/zk-kit/commit/0699fd1e5ad3683ae0090e0626f75d7834145500#r141218878).
> chore: increase timeout test

- .github/workflows/production.yml
- .github/workflows/pull-requests.yml
Fix #263 so that it is easier to read the workflow logs and see which tests group may be failing. (Current failing `test:contracts` job needs #262 to succeed)
It does not seem to have any impact all the timeout issues we experienced latest in some tests (see #240 or #262).  
|Before|After|
|---|---|
|![image](https://github.com/privacy-scaling-explorations/zk-kit/assets/38692952/e417f566-68e4-4f4d-a2ad-dd2361b6d840)|![image](https://github.com/privacy-scaling-explorations/zk-kit/assets/38692952/629087be-b582-4a99-9d98-f904304534ce)|
> ci: split tests in multiple concurrent jobs in pr workflow

- packages/eddsa-proof/README.md
- packages/eddsa-proof/package.json
- packages/eddsa-proof/src/generate.ts
- packages/eddsa-proof/src/hash.ts
- packages/eddsa-proof/src/to-bigint.ts
- packages/eddsa-proof/tests/index.test.ts
- packages/poseidon-proof/README.md
- packages/poseidon-proof/package.json
- packages/poseidon-proof/src/generate.ts
- packages/poseidon-proof/src/hash.ts
- packages/poseidon-proof/src/to-bigint.ts
- packages/poseidon-proof/src/types/index.ts
- packages/poseidon-proof/src/verify.ts
- packages/poseidon-proof/tests/index.test.ts
- yarn.lock
This PR changes the type of the `scope` parameter in the following packages: `@zk-kit/eddsa-proof`, `@zk-kit/poseidon-proof`. `scope` can now also be text.
Additionally, it include the number of inputs of the `poseidon-proof` package in the proof object, so that the `verify` function doesn't need it as a separate parameter. 
Closes #214
-   [x] New and existing …
> refactor!: change types for scope parameter

- .github/workflows/pull-requests.yml
This PR skips contract tests when changes are unrelated to contract files. Specifically, contract tests will only be triggered if files under `packages/**/*.sol` are modified
> ci: skip contract tests when PR changes are unrelated

- packages/utils/package.json
This PR removes the `snark-artifacts` exports from the package.json file in the utils package, as that module no longer exists.
Closes #287
> chore(utils): remove unexisting snark-artifacts exports

- packages/poseidon-proof/package.json
- yarn.lock
`maybeGetSnarkArtifacts` from `@zk-kit/artifacts@1.4.1` includes a retry mechanism as a workaround against the rate limiting issue we have been experiencing with unpkg.com
Closes #280
Mirror of https://github.com/semaphore-protocol/semaphore/pull/798
> chore(poseidon-proof): bump `@zk-kit/artifacts`

- packages/eddsa-poseidon/src/eddsa-poseidon.ts
- packages/eddsa-poseidon/tests/index.test.ts
The private key must always be 1 of the following supported types: buffer, uint8array, or text. The default private key generated in the constructor was a hexadecimal string and it was considered text by the internal functions. The default private key is a buffer now, which eliminates the ambiguity.
Fixes #297
> fix(eddsa-poseidon): set default private key as buffer

- packages/poseidon-proof/README.md
- packages/poseidon-proof/package.json
- yarn.lock
1.8.0 uses the new pse public cdn to download artifacts:
ex: https://snark-artifacts.pse.dev/poseidon/latest/poseidon-4.wasm
> chore: bump `@zk-kit/artifacts` to `1.8.0`

- .github/CODEOWNERS
- README.md
- package.json
- packages/logical-expressions/LICENSE
- packages/logical-expressions/README.md
- packages/logical-expressions/build.tsconfig.json
- packages/logical-expressions/package.json
- packages/logical-expressions/rollup.config.ts
- packages/logical-expressions/src/evaluate.ts
- packages/logical-expressions/src/index.ts
- packages/logical-expressions/src/tokenize.ts
- packages/logical-expressions/tests/index.test.ts
- packages/logical-expressions/tsconfig.json
- packages/logical-expressions/typedoc.json
- yarn.lock
This PR:
- Moves the code to evaluate logical expressions from the [Bandada](https://github.com/bandada-infra/bandada/blob/main/libs/credentials/src/evaluateExpression.ts) project to a new package called `@zk-kit/logical-expressions`.
- The `evaluate` function now throws an error if the logical expression is incorrect.
There is no need to verify the correctness of the logical expression before calling the evaluate function, as this will be checked during the evaluation. If the expression is incorrect, an error will be thrown automatically.  
Example of correct logical expression: `"true and false"`.
Example of incorrect logical expression: `"true true and false"`.
The `@zk-kit/logical-expressions` package facilitates the work with logical (boolean) expressions. It allows you to tokenize …
> feat: add `@zk-kit/logical-expressions` package

- README.md
Added FAQ to guide the developers about when and why use a specific type of Merkle tree for their projects
The FAQ has a short text answer plus a comparison table with more detailed data Refs: #311
docs: add section to help choose merkle tree [#311](https://github.com/privacy-scaling-explorations/zk-kit/issues/311)
It would be helpful to write a comparison of of all them, answering questions like
-   [x] "when not to use"/"when to use"
-   [x]  "used by?": protocol xyz, app xyz...
-   [ ] include benchmarks: maybe one merkle tree is faster at generating a proof, but slower to update?
> docs: added Merkle tree use recommendations

- .lintstagedrc.json
- README.md
- papers/leanimt/README.md
This PR adds the download paper link to make it easier to download the PDF document.
> docs: add paper download link to readme files

- papers/leanimt/README.md
The command provided for adding a path to `~/.zshrc` uses the `-n` flag with `echo`:
```bash
echo -n 'export PATH=$HOME/bin:$PATH' >> ~/.zshrc
```
The `-n` flag suppresses the newline, which can cause the appended line to merge with the last line in `~/.zshrc`. This may lead to configuration errors, especially if the file does not end with a newline.
The corrected command removes the `-n` flag:
```bash
echo 'export PATH=$HOME/bin:$PATH' >> ~/.zshrc
```
This ensures proper appending of the line, preventing potential issues with shell configuration.
This fix is crucial for ensuring that users setting up LaTeX on Mac systems follow accurate and reliable instructions. Incorrect configurations can lead to debugging challenges, particularly for users unfamiliar with shell scripting or …
> Typo fix Update README.md

- packages/imt/src/imt.ts
- packages/imt/tests/imt.test.ts
In order to improve performance, we can avoid recalculating the Incremental Merkel Tree in the event that the update value is the same as the tree value.
Closes #340
> perf(imt): when updating a node, skip calculation if value is the same

- README.md
This PR updates two incorrect links in the `README.md` file:  
- Fixed the `poseidon-cipher` documentation link to point to the correct URL.  
- Updated the `logical-expressions` documentation link to the correct URL.  
These changes ensure that users can access the correct documentation for the corresponding packages.
> Fix broken and incorrect links README.md

- benchmarks/README.md
This PR fixes spelling errors in the benchmarks documentation to improve clarity and technical accuracy.
1. Changed "leafs" to "leaves" (correct plural form)
2. Changed "theorical" to "theoretical" (correct spelling)
Before:
The Benchmarks suggested in the index.ts are for **8, 128 and 1024 leafs** to see how each Merkle tree for different sizes of trees perform because their theorical expected behavior...
After:
The Benchmarks suggested in the index.ts are for **8, 128 and 1024 leaves** to see how each Merkle tree for different sizes of trees perform because their theoretical expected behavior...
1. "Leaves" is the correct plural form of "leaf" in technical contexts, especially when referring to tree data structures
2. "Theoretical" is the correct spelling of the word describing concepts …
> Update README.md - Fix Spelling and Grammar

- packages/smt/src/smt.ts
It's the nittiest of nits, but helps a lot if for whatever reason you want to use 0 as entry marker for the leaves in an SMT
> feat(smt): allow ChildNodes to use 0 as entry marker

- packages/smt/README.md
This pull request addresses a minor grammatical issue in the `README.md` file. The phrase "an Hexadecimal" was changed to "a Hexadecimal" to correctly follow the rule of using "a" before words starting with a consonant sound. This small correction ensures the clarity and accuracy of the documentation.
**Checklist**:
> Fix grammar in README.md

- packages/imt/src/types/index.ts
Changed `IMTNode` type from `any` to `number | string | bigint` to make it clearer.
Fixes #339 
-   [x] I have read and understand the [contributor guidelines](https://github.com/privacy-scaling-explorations/zk-kit/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/privacy-scaling-explorations/zk-kit/blob/main/CODE_OF_CONDUCT.md).
-   [] I have added tests that prove my fix is effective or that my feature works
> [!IMPORTANT]
> We do not accept minor grammatical fixes (e.g., …
> refactor(imt): define export type IMTNode instead of any

- packages/utils/src/error-handlers.ts
- packages/utils/src/type-checks.ts
- packages/utils/tests/error-handlers.test.ts
- packages/utils/tests/type-checks.test.ts
This PR adds support to check boolean values in the `TypeChecks` and `ErrorHandlers` modules.
Closes #372
-   [x] I have read and understand the [contributor guidelines](https://github.com/privacy-scaling-explorations/zk-kit/blob/main/CONTRIBUTING.md) and [code of conduct](https://github.com/privacy-scaling-explorations/zk-kit/blob/main/CODE_OF_CONDUCT.md).
> [!IMPORTANT]
> We do not accept minor grammatical fixes …
> feat(utils): support boolean in types-checks and error-handlers

- packages/lean-imt/src/lean-imt.ts
This PR replaces the spread operator (previously used with push) in the `insertMany` function with `concat`. This change allows `insertMany` to handle a large number of members efficiently, such as 110 000.
This improvement is particularly beneficial for initializing the LeanIMT, as it relies on `insertMany` internally to populate the tree with members.
After running benchmarks, I chose `concat` because it is by far the fastest and simplest solution.
1. Use `concat` (chosen solution).
2. Use a for loop with push.
3. Use a chunking approach (adding members in chunks of 10 000 with push).
All the benchmarks were run in an environment with these properties:
Computer: MacBook Pro
Chip: Apple M2 Pro
Memory (RAM): 16 GB
Operating System: macOS Sequoia version 15.3
Node.js version: 22.11.0 …
> fix(lean-imt): replace the spread operator inside the push function with concat

- packages/poseidon-cipher/README.md
- packages/poseidon-cipher/src/poseidonCipher.ts
This PR addresses the security vulnerability identified in issue #341 regarding JavaScript's native BigInt implementation in the poseidon-cipher package. The BigInt operations are not constant-time and could potentially be vulnerable to timing attacks.
As an interim solution while waiting for a constant-time library implementation, I've added clear security warnings to:
The README.md file - Added a prominent warning box after the badges section, before the main content
The poseidonCipher.ts source file - Added detailed JSDoc-style warning comments before the function definitions
Both warnings explain the nature of the vulnerability, link to Mozilla's documentation about BigInt cryptographic limitations, and reference the GitHub issue for tracking. The warnings are designed to inform users …
> Add security warning about BigInt vulnerability
